version: "3.8"

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ./bazarr/config:/config
      - /home/user/media:/data
      - /mnt/dysk_usb:/usb_data
    ports:
      - 6767:6767
    restart: unless-stopped

  unpackerr:
    image: golift/unpackerr:latest
    container_name: unpackerr
    volumes:
      - /home/user/media:/data
      - /mnt/dysk_usb:/usb_data
    environment:
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=YOUR_SONARR_API_KEY
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=YOUR_RADARR_API_KEY
      - UN_DELETE_DELAY=5m
      - UN_DELETE_ORIGINAL=false
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - /home/user/media:/data
      - /mnt/dysk_usb:/usb_data
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ./radarr/config:/config
      - /home/user/media:/data
      - /mnt/dysk_usb:/usb_data
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ./sonarr/config:/config
      - /home/user/media:/data
      - /mnt/dysk_usb:/usb_data
    ports:
      - 8989:8989
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Warsaw
    ports:
      - 8191:8191
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - "5055:5055"
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Warsaw
    volumes:
      - ./jellyseerr-config:/app/config

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    network_mode: "host"
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /home/user/media:/media
      - /mnt/dysk_usb/media:/usb_media

volumes:
  jellyfin-config:
  jellyfin-cache:
